set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(THOR_TOOLCHAIN_ROOT "/usr/local/thor/aarch64--glibc--bleeding-edge-2024.02-1" CACHE PATH "Thor aarch64 cross toolchain root")
set(THOR_CROSS_PREFIX "aarch64-linux" CACHE STRING "Thor cross compiler executable prefix")

set(CMAKE_C_COMPILER "${THOR_TOOLCHAIN_ROOT}/bin/${THOR_CROSS_PREFIX}-gcc" CACHE FILEPATH "C compiler")
set(CMAKE_CXX_COMPILER "${THOR_TOOLCHAIN_ROOT}/bin/${THOR_CROSS_PREFIX}-g++" CACHE FILEPATH "C++ compiler")
set(CMAKE_AR "${THOR_TOOLCHAIN_ROOT}/bin/${THOR_CROSS_PREFIX}-ar" CACHE FILEPATH "Archiver")
set(CMAKE_RANLIB "${THOR_TOOLCHAIN_ROOT}/bin/${THOR_CROSS_PREFIX}-ranlib" CACHE FILEPATH "Ranlib")
set(CMAKE_STRIP "${THOR_TOOLCHAIN_ROOT}/bin/${THOR_CROSS_PREFIX}-strip" CACHE FILEPATH "Strip")

if(DEFINED ENV{THOR_SYSROOT} AND NOT "$ENV{THOR_SYSROOT}" STREQUAL "")
  set(CMAKE_SYSROOT "$ENV{THOR_SYSROOT}" CACHE PATH "Thor target sysroot")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
