#!/usr/bin/env python3
"""Create an isolated Yangluo ResNet50 config from the verified adapter YAML."""

import argparse
from pathlib import Path


BACKBONE_BEGIN = "      backbone:\n"
BACKBONE_END = "      neck:\n"


def replace_backbone(text: str, pretrained: str) -> str:
    begin = text.find(BACKBONE_BEGIN, text.find("    camera:"))
    if begin < 0:
        raise RuntimeError("camera backbone block was not found")
    end = text.find(BACKBONE_END, begin)
    if end < 0:
        raise RuntimeError("camera neck block was not found")
    block = (
        "      backbone:\n"
        "        type: ResNet\n"
        "        depth: 50\n"
        "        num_stages: 4\n"
        "        out_indices: [1, 2, 3]\n"
        "        frozen_stages: -1\n"
        "        norm_cfg:\n"
        "          type: BN\n"
        "          requires_grad: true\n"
        "        norm_eval: false\n"
        "        style: pytorch\n"
        "        init_cfg:\n"
        "          type: Pretrained\n"
        f"          checkpoint: {pretrained}\n"
    )
    text = text[:begin] + block + text[end:]
    old = "        in_channels: [192, 384, 768]"
    if old not in text:
        raise RuntimeError("Swin camera-neck channel signature was not found")
    return text.replace(old, "        in_channels: [512, 1024, 2048]", 1)


def disable_full_model_checkpoint(text: str) -> str:
    """Start BEVFusion from scratch apart from the ResNet50 init_cfg."""
    lines = text.splitlines(keepends=True)
    replaced = {"load_from": False, "resume_from": False}
    for index, line in enumerate(lines):
        for key in replaced:
            if line.startswith(f"{key}:"):
                newline = "\r\n" if line.endswith("\r\n") else "\n"
                lines[index] = f"{key}: null{newline}"
                replaced[key] = True
    missing = [key for key, found in replaced.items() if not found]
    if missing:
        raise RuntimeError(f"top-level checkpoint fields were not found: {missing}")
    return "".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--pretrained", required=True)
    args = parser.parse_args()

    source = Path(args.input)
    destination = Path(args.output)
    text = source.read_text(encoding="utf-8")
    if "type: SwinTransformer" not in text:
        raise RuntimeError("input config is not the expected Swin Yangluo config")
    text = disable_full_model_checkpoint(text)
    text = replace_backbone(text, Path(args.pretrained).as_posix())
    text = (
        "# Generated by yangluo_deploy/training/make_resnet50_config.py\n"
        "# Full-model load/resume is disabled; only ResNet50 init_cfg is pretrained.\n"
        + text
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(text, encoding="utf-8")
    print(f"PASS resnet50_config={destination}")


if __name__ == "__main__":
    main()
